"""Add novos campos contatos_novo_convertido_acoes

Revision ID: 6a1ad07901c1
Revises: cb09ef341a5b
Create Date: 2025-12-28 00:42:22.770800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1ad07901c1'
down_revision: Union[str, Sequence[str], None] = 'cb09ef341a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contatoNovoConvertido', sa.Column('status_contato', sa.String(length=50), nullable=False))
    op.add_column('contato_novo_convertido_acoes', sa.Column('motivo_nao_manter_contato', sa.String(length=1000), nullable=True))
    op.add_column('contato_novo_convertido_acoes', sa.Column('cadidato_abandonou_discipulado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contato_novo_convertido_acoes', sa.Column('motivo_abandono_discipulado', sa.String(length=1000), nullable=True))
    op.add_column('contato_novo_convertido_acoes', sa.Column('agendar_proximo_contato_data', sa.Date(), nullable=True))
    op.add_column('contato_novo_convertido_acoes', sa.Column('agendar_proximo_contato_hora', sa.String(length=8), nullable=True))
    op.add_column('contato_novo_convertido_acoes', sa.Column('candidato_preparado_batismo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contato_novo_convertido_acoes', sa.Column('data_batismo', sa.Date(), nullable=True))
    op.add_column('contato_novo_convertido_acoes', sa.Column('candidato_esta_em_duvidas_batismo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contato_novo_convertido_acoes', sa.Column('motivo_duvidas_batismo', sa.String(length=1000), nullable=True))
    op.add_column('contato_novo_convertido_acoes', sa.Column('candidato_desistiu_batismo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('contato_novo_convertido_acoes', sa.Column('motivo_desistencia_batismo', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_contato_novo_convertido_acoes_id'), 'contato_novo_convertido_acoes', ['id'], unique=False)
    op.create_index(op.f('ix_novos_convertidos_id'), 'novos_convertidos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_novos_convertidos_id'), table_name='novos_convertidos')
    op.drop_index(op.f('ix_contato_novo_convertido_acoes_id'), table_name='contato_novo_convertido_acoes')
    op.drop_column('contato_novo_convertido_acoes', 'motivo_desistencia_batismo')
    op.drop_column('contato_novo_convertido_acoes', 'candidato_desistiu_batismo')
    op.drop_column('contato_novo_convertido_acoes', 'motivo_duvidas_batismo')
    op.drop_column('contato_novo_convertido_acoes', 'candidato_esta_em_duvidas_batismo')
    op.drop_column('contato_novo_convertido_acoes', 'data_batismo')
    op.drop_column('contato_novo_convertido_acoes', 'candidato_preparado_batismo')
    op.drop_column('contato_novo_convertido_acoes', 'agendar_proximo_contato_hora')
    op.drop_column('contato_novo_convertido_acoes', 'agendar_proximo_contato_data')
    op.drop_column('contato_novo_convertido_acoes', 'motivo_abandono_discipulado')
    op.drop_column('contato_novo_convertido_acoes', 'cadidato_abandonou_discipulado')
    op.drop_column('contato_novo_convertido_acoes', 'motivo_nao_manter_contato')
    op.drop_column('contatoNovoConvertido', 'status_contato')
    # ### end Alembic commands ###
