"""contatos novo convertido acoes

Revision ID: b043f441bc13
Revises: 0b17df3c2ecf
Create Date: 2025-12-19 10:11:13.296185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b043f441bc13'
down_revision: Union[str, Sequence[str], None] = '0b17df3c2ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contatoNovoConvertido_contact_event_id'), table_name='contatoNovoConvertido')
    op.drop_index(op.f('ix_contatoNovoConvertido_id'), table_name='contatoNovoConvertido')
    op.drop_index(op.f('ix_contatoNovoConvertido_protocolo'), table_name='contatoNovoConvertido')
    op.drop_table('contatoNovoConvertido')
    op.drop_index(op.f('ix_novos_convertidos_id'), table_name='novos_convertidos')
    op.drop_table('novos_convertidos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novos_convertidos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cep', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('complemento', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cidade', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bairro', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('uf', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('data_cadastro', sa.DATE(), nullable=False),
    sa.Column('idade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('data_conversao', sa.DATE(), nullable=False),
    sa.Column('discipulador_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['discipulador_id'], ['users.id'], name='1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_novos_convertidos_id'), 'novos_convertidos', ['id'], unique=False)
    op.create_table('contatoNovoConvertido',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('discipulador_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('novo_convertido_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sucesso_contato', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('data_contato', sa.DATE(), server_default=sa.text('curdate()'), nullable=False),
    sa.Column('contact_event_id', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('protocolo', mysql.VARCHAR(length=26), nullable=False),
    sa.Column('hora_protocolo', mysql.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['discipulador_id'], ['users.id'], name=op.f('1')),
    sa.ForeignKeyConstraint(['novo_convertido_id'], ['novos_convertidos.id'], name=op.f('2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_contatoNovoConvertido_protocolo'), 'contatoNovoConvertido', ['protocolo'], unique=True)
    op.create_index(op.f('ix_contatoNovoConvertido_id'), 'contatoNovoConvertido', ['id'], unique=False)
    op.create_index(op.f('ix_contatoNovoConvertido_contact_event_id'), 'contatoNovoConvertido', ['contact_event_id'], unique=True)
    # ### end Alembic commands ###
